project:
  type: website
  output-dir: docs


website:
  title: "EMPRA"
  favicon: assets/images/logo-square.png
  site-url: https://alexander-pastukhov.github.io/empra
  navbar:
    logo: assets/images/logo-small.svg
    left:
      - href: index.qmd
        text: Home
      - href: going-further.qmd
        text: Going Further

format:
  html:
    theme:
    - cosmo
    - empra.scss
    css: styles.css
    head-content: |
      <link href="https://fonts.googleapis.com/css2?family=Lustria&display=swap" rel="stylesheet">
    toc: true

babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: de
    text: "Deutsch"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['de']
title-de: EMPRA
lang: en
